### ISSUE TITLE
Ideas to promote the project

### ISSUE THREAD

**Issue by noraj** [jollheef/henhouse#8]
Some ideas : 
- add tags to the repository like ctf, ctf-scoreboard, ctf-platform, etc...
- make screenshots

You will be soon linked here http://list.rawsec.ml/ctf_platforms.html

**Comment by jollheef** [comment]
I added tags to the current repository and to another for attack-defense (https://github.com/jollheef/tin_foil_hat).

Screenshots will be a later :)

**Comment by noraj** [comment]
@jollheef looks great now
