### ISSUE TITLE
В лог иногда записывается некорректная информация об открытой задаче

### ISSUE THREAD

**Issue by MikeLupanov** [jollheef/henhouse#9]
При записи в лог иногда записывается некорректная информация об открытой задаче.
Например, задача B автоматически открывается после решения задачи A. В лог записывается информация, что открылась задача A, хотя на самом деле открылась B.
`2017/10/31 21:20:19 Open task Братан, это матан 3`
`2017/10/31 21:21:16 Team ID: 1, Task ID: 2, Flag: xxxxxxxxxxxxx, Result: <div class="flag_status solved">Solved</div>`
`2017/10/31 21:22:16 Open task Братан, это матан 3`

**Comment by jollheef** [comment]
Исправлено в e8e60ce, версия пакета начиная с henhouse_1.1.1-15_amd64.deb.
